### ISSUE TITLE
Do not deprecate digraph forms like >=

### ISSUE THREAD

**Issue by martmists** [shreyasminocha/nirvana#1]
This is an issue to open discussion based on this line in the Readme:
> Eventually, I plan on supporting unicode characters like “≥” and deprecating their digraph alternatives like “>=”.

Many developers (including me) prefer the digraph alternatives as they are easier to type, but also use a font with ligatures to make these more easily distinguishable.

Example:

| Kate (no ligatures)                                                                                            | IDEA (ligatures, Fira Code)                                                                                    |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/16361449/47954614-2db43380-df8c-11e8-9b6d-84bb437d2430.png) | ![image](https://user-images.githubusercontent.com/16361449/47954623-4290c700-df8c-11e8-8887-03588364d5fc.png) |

Additionally, the single unicode variants are very uncommon on keyboards and many users do not know the alt codes by heart. I would encourage adding support, but discourage deprecating the standard digraphs.

**Comment by shreyasminocha** [comment]
Yes, I'm getting this a lot. 

> I would encourage adding support, but discourage deprecating the standard digraphs.

Just what I'm going to do.
