### ISSUE TITLE
Why Nirvana?

### ISSUE THREAD

**Issue by sebasgarcep** [shreyasminocha/nirvana#4]
After skimming through the README I don't see any new ideas that would make this language easier to mantain or read when compared with traditional OOP languages, which seems to be the main purpose of this project.

You might want to check out languages like Haskell, Rust or Elm which have a plethora of ideas that stray away from traditional OOP and bring added value.

**Comment by shreyasminocha** [comment]
I see that your point. Perhaps I'll make my readme less of an attempt to sway people to use this. My primary goal is _learning_ but I aimed to also create a language that I (and possibly others) will enjoy programming in. Yeah, you're probably right in that I'm not introducing too many new things. I will try to come up with distinguishing features in due course of time, but I'll also make it more explicit that I'm in no way an expert and that I'm primarily trying to learn something new.
