### ISSUE TITLE
"not" - logical operator or function

### ISSUE THREAD

**Issue by rakhack** [shreyasminocha/nirvana#6]
Readme provides an example of logical operators, exposing NOT as a function, not an operator.

    bool isEven = not(isOdd);

Reading readme I was wondering if this has a particular reason, or it is an example of using parentheses with logical operators, or an oversight?

**Comment by shreyasminocha** [comment]
It's meant to be an operator, and yes, it is an example of using parentheses with logical operators. Will make it more clear in the readme. Thanks!

**Comment by rakhack** [comment]
I can send you a PR if you want :smile:, fixing things and making suggestions will probably be faster this way in the future.

**Comment by shreyasminocha** [comment]
I'd appreciate that! 😄
